### ISSUE TITLE
Handle errors in attribute iteration

### ISSUE THREAD

**Issue by philipc** [fitzgen/gimli#21]
`EntriesCursor::next_dfs` doesn't handle errors:
https://github.com/fitzgen/gimli/blob/8e4eb3ce54a966b5bd17b396ff279858d794b162/src/parser.rs#L3388-L3389

`EntriesCursor::next_sibling` has a related problem at: https://github.com/fitzgen/gimli/blob/8e4eb3ce54a966b5bd17b396ff279858d794b162/src/parser.rs#L3526

Part of the problem is that `AttrsIter::next` leaves the iterator in a state that won't continue to give errors: https://github.com/fitzgen/gimli/blob/8e4eb3ce54a966b5bd17b396ff279858d794b162/src/parser.rs#L3091. So if an error does occur, the next DIE will start being parsed at wherever the error occurred, with unpredictable results.

(Note: the above is all from code inspection, I haven't tested this happens yet, so I may be mistaken.)

It's easy to get this wrong when using `Option<Result<...>>`. We could switch to `Result<Option<...>>`, but that loses the ergonomics of `for` loops.  Some of the iterator functions can be retained using https://github.com/sfackler/rust-fallible-iterator.

**Comment by fitzgen** [comment]
Yes, those places should be checking for errors and setting the input to the empty slice so that the cursor is no longer usable.

> It's easy to get this wrong when using Option<Result<...>>. We could switch to Result<Option<...>>, but that loses the ergonomics of for loops. Some of the iterator functions can be retained using https://github.com/sfackler/rust-fallible-iterator.

This seems like a good idea to me.
