### ISSUE TITLE
Should the parser be generic over anything that implements `std::io::Read`?

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/gimli#3]
Right now, `gimli` parses `&[u8]` slices, which means that the DWARF section being parsed needs to be completely in memory. Will this be a problem in practice? Is it worth the extra implementation and API complexity to make the input any generic `std::io::Read` type? Might need to also require `std::io::Seek` for following `DW_AT_sibling` references.

@tromey @jimblandy: can I lean on your experiences with GDB for guidance?

cc @philipc

**Comment by fitzgen** [comment]
Another thing to think about: how would this affect the zero-copy nature of the library that we currently have?

**Comment by jimblandy** [comment]
I think you should just mmap the file.

**Comment by jimblandy** [comment]
GDB mmaps individual sections of the executable file. But if we assume 64-bit address spaces  (well, 48-bit, that's still ~300 TiB), I don't see anything really bad happening if you just map in the whole file.

**Comment by fitzgen** [comment]
Thanks!

No need to be generic over the input then.
