### ISSUE TITLE
LineNumberProgramHeader can't reliably iterate twice

### ISSUE THREAD

**Issue by philipc** [fitzgen/gimli#40]
`LineNumberProgramHeader::file_names` has interior mutability, which is incompatible with multiple `StateMachine`s using it.

**Comment by fitzgen** [comment]
Yeah, `StateMachine` should consume the `LineNumberProgramHeader`, which is fine as long as `LineNumberProgramHeader` is `Clone` so that the program can still be executed multiple times if that is needed for whatever reason.

**Comment by fitzgen** [comment]
I'll do this after your PR is merged.
