### ISSUE TITLE
Need a method to obtain the abbreviations for a CompilationUnit

### ISSUE THREAD

**Issue by philipc** [fitzgen/gimli#5]
Should be able to replace https://github.com/philipc/rust-dwarf/blob/master/benches/bench.rs#L48-L50 with
`let abbrevs = unit.abbreviations(&debug_abbrev);`
or
`let abbrevs = debug_abbrev.abbreviations(unit.debug_abbrev_offset());`
(not sure which way is best).

**Comment by fitzgen** [comment]
I meant to add this to the TODO list but it slipped my mind. Good catch!

I mildly prefer the former.
